module.exports = [
  {
    name: "Admin",
    description: "Quản trị viên toàn hệ thống",
    claims: [
      "banUser",
      "unbanUser",
      "approvePost",
      "deleteComment",
      "editAnyPost ",
      "accessAdminPanel",
      "sendSystemMessage",
      "viewAnalytics ",
      "manageBadWords ",
    ],
    managePost: true,
    manageUser: true,
    canCreateNews: true,
    canViewReports: true,
    canManageTopicsTags: true,
  },
  {
    name: "Moderator",
    description: "Kiểm duyệt viên",
    claims: ["deleteComment", "manageBadWords"],
    managePost: true,
    manageUser: false,
    canCreateNews: false,
    canViewReports: true,
    canManageTopicsTags: true,
  },
  {
    name: "Member",
    description: "Thành viên diễn đàn",
    claims: ["createPost", "comment", "react", "report"],
    managePost: false,
    manageUser: false,
    canCreateNews: false,
    canViewReports: false,
    canManageTopicsTags: false,
  },
];
